name: GitHub Snake

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */12 * * *'  # ogni 12 ore

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Setup git for push
        run: git remote set-url origin https://$PAT_TOKEN@github.com/${{ github.repository }}.git
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
    
      - name: Commit & push generated images
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/
          git diff --cached --quiet || git commit -m "Update GitHub Snake"
          git push
